### ISSUE TITLE
Change Duty Cycle

### ISSUE THREAD

**Issue by AnselPeng2019** [khoih-prog/ESP8266_PWM#1]
when I use this lib, after setup the PWM paras, the PWM works well. But I need to change the duty cycle in working, for example, the breathing led.

I have tried to use disable or delete function, but it looks not work, the PWM duty cycle do not change.

So,  it would be great if there is a duty cycle set up function.

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

> I have tried to use disable or delete function, but it looks not work, the PWM duty cycle do not change.

Please follow the instructions when opening a new issue and post the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example) sketches to save time for anybody trying to reproduce the issue.

Waiting for your response,

**Comment by khoih-prog** [comment]
Hi,

I just add an example [**ISR_Changing_PWM**](https://github.com/khoih-prog/ESP8266_PWM/tree/main/examples/ISR_Changing_PWM) to show you how to change PWM freq and duty-cycle on-the-fly.

Anyway, I'll add option to make it easier to change the PWM freqs and duty-cycles, without having to delete and reinit the PWM channels in next release.

**Comment by khoih-prog** [comment]
Hi @AnselPeng2019 

The new [**ESP8266_PWM releases v1.1.0**](https://github.com/khoih-prog/ESP8266_PWM/releases/tag/v1.1.0) has just been published

Your contribution has been noted in [**Contributions and Thanks**](https://github.com/khoih-prog/ESP8266_PWM#contributions-and-thanks)

Check the new

1. [**ISR_Changing_PWM** example](https://github.com/khoih-prog/ESP8266_PWM/tree/main/examples/ISR_Changing_PWM) 
2. [**ISR_Modify_PWM** example](https://github.com/khoih-prog/ESP8266_PWM/tree/main/examples/ISR_Modify_PWM) 

The library is definitely better and more useful now. Looking forward to receiving more enhancement requests from you.

Best Regards,

KH

---

## Changelog

### Releases v1.1.0

1. Add functions to modify PWM settings on-the-fly
2. Fix bug
3. Add example to demo how to modify PWM settings on-the-fly

**Comment by ggmichael** [comment]
I'm similarly trying to change the duty cycle with a fixed frequency. Since PWM_DutyCycle is a uint32_t , this can only be done in 100 steps. I suggest to have an alternative function where you can specify Period/OnTime to be able to get the full duty cycle resolution. Or change PWM_DutyCycle to a float (I think 0. to 1. would be easier to use than 0-100 if you do this).

**Comment by khoih-prog** [comment]
@ggmichael 

Good idea. I'll rewrite the library to use **float / double** for PWM `freqs`, `period` and `duty-cycles` to have much better accuracy.

Regards,

**Comment by khoih-prog** [comment]
Hi @ggmichael 


The new [**ESP8266_PWM releases v1.2.0**](https://github.com/khoih-prog/ESP8266_PWM/releases/tag/v1.2.0) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/ESP8266_PWM#contributions-and-thanks)

Best Regards,

---

### Releases v1.2.0

1. Fix `multiple-definitions` linker error. Drop `src_cpp` and `src_h` directories
2. Add feature to **select among highest, medium or lowest accuracy** for Timers for shortest, medium or longest time
3. Fix reattachInterrupt() bug. Check [bugfix: reattachInterrupt() pass wrong frequency value to setFrequency() #19](https://github.com/khoih-prog/ESP8266TimerInterrupt/pull/19)
4. Add example [**multiFileProject**](examples/multiFileProject) to demo for multiple-file project
5. **Improve accuracy** by using `double`, instead of `uint32_t` for `dutycycle`, `period`. Check [**Change Duty Cycle** #1](https://github.com/khoih-prog/ESP8266_PWM/issues/1#issuecomment-1024969658)
6. Update examples accordingly

**Comment by ggmichael** [comment]
Thanks for this! Your library has fixed a problem I was having with inconsistent calibration, which I now think arose from the changing timing of the analogWrite pwm. 

One more feature that would be nice would be to be able to command a duty cycle update to occur at the end of the next full period instead of immediately (as I think happens now). If you're trying to create a continuously variable mean output voltage, resetting the channel at a frequency that approaches the PWM frequency causes a bias towards whichever part of the duty cycle comes first. This wouldn't happen if the update occurred at the end of the cycle. It may be that there are other applications (long cycles) where you would prefer the update straight away. So perhaps a flag to set either mode.

**Comment by khoih-prog** [comment]
Hi @ggmichael

> One more feature that would be nice would be to be able to command a duty cycle update to occur **at the end of the next full period** instead of immediately (as I think happens now)

It's nice-to-have and a little bit harder, but totally possible to address this issue, if there are many more users requesting the similar feature.

Can you start by creating a **new enhancement request / issue**, and also specify the **use-case** and how it'll be beneficial to have the new feature.

IMO, a short `glitch` can't affect anything (such as light, motor control, etc.). I also don't think `analogWrite pwm` has taken care of this issue.

Thanks,
